services:
  - type: web
    name: academic-crm
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false
    healthCheckPath: /api/health