apiVersion: v1
kind: ServiceAccount
metadata:
  name: academic-crm-sa
  namespace: academic-crm
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: academic-crm
  name: academic-crm-role
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: academic-crm-rolebinding
  namespace: academic-crm
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: academic-crm-sa
  namespace: academic-crm
roleRef:
  kind: Role
  name: academic-crm-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: academic-crm-netpol
  namespace: academic-crm
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: academic-crm
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: academic-crm-monitoring
    ports:
    - protocol: TCP
      port: 5000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: LimitRange
metadata:
  name: academic-crm-limits
  namespace: academic-crm
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: security
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2000m"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: academic-crm-quota
  namespace: academic-crm
  labels:
    app.kubernetes.io/name: academic-crm
    app.kubernetes.io/component: security
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "20"
    configmaps: "20"