services:
  - type: web
    name: academic-management-platform
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: academic-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: academic-db
    databaseName: academic_platform
    user: academic_user