name: Auto Update Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update dependencies
      run: |
        npx npm-check-updates -u
        npm install
        
    - name: Run tests after update
      run: |
        npm run check
        npm run build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## 🔄 Automated Dependency Update
          
          This PR contains automated dependency updates generated by GitHub Actions.
          
          ### Changes Made:
          - Updated all npm dependencies to latest versions
          - Verified build and type checking passes
          - Maintained compatibility with existing codebase
          
          ### Testing:
          - ✅ TypeScript compilation successful
          - ✅ Build process completed without errors
          - ✅ No breaking changes detected
          
          Please review the changes and merge if everything looks good!
        branch: automated-dependency-updates
        delete-branch: true